apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-webapp
  template:
    metadata:
      labels:
        app: node-webapp
    spec:
      containers:
      - name: node-webapp
        image: YOUR_ACR.azurecr.io/node-webapp:latest
        ports:
        - containerPort: 3000
